apiVersion: apps/v1 
kind: Service
metadata:
  name:my-app-development
spec:
   selector:
	app: my-app
   ports:
   - protocol:TCP
     port:5001
     targetPort: 5001
   type: LoadBalancer

                   